baseurl: "/"
permalink: pretty
title: "MemChain AI"
description: "Enterprise-Grade Memory Management Platform for AI - MemChain provides intelligent memory backbone for AI systems with human-like memory capabilities."
url: "https://www.memchain.ai"
# Override for production builds
production_url: "https://www.memchain.ai"
author: "MemChain AI"
twitter:
  username: memchainai
  card: summary_large_image

# Logo configuration for Jekyll SEO
logo: "/images/logo/logo-memchain.svg"

# Custom logo configuration for theme
theme_logo:
  mobile: "images/logo/isotype-memchain.svg"
  mobile_height: "48px"
  mobile_width: "48px"
  desktop: "images/logo/logo-memchain.svg"
  desktop_height: "100px"
  desktop_width: "200px"

fonts:
  use_google_fonts: true
  google_fonts_url: "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600;700&display=swap"
  use_self_hosted_fonts: false
  heading: "Roboto Sans"
  base: "Inter"
  monospace: "Roboto Mono"
  logo: "Roboto Sans"

home:
  limit_capabilities: 6

collections:
  capabilities:
    output: true
    sort_by: weight
  memorytypes:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: "/"
      type: "capabilities"
    values:
      layout: "capability"
  - scope:
      path: "/"
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
